name: send_mms
description: A Plugin that allows you to attach an image as MMS and message with the default messaging app.
version: 0.0.1
author: Ammonious <Ammonious@gmail.com>
homepage: https://github.com/Ammonious/send_mms

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    platforms:
      android:
        package: com.schemecreative.send_mms
        pluginClass: SendMmsPlugin
        iosPrefix: FLT


